import type { Metadata } from "next"

import "./globals.css"

import TanstackProvider from "@/features/tanstack/components/TanstackProvider"
import CenterStageLayout from "@/features/layout/components/CenterStageLayout"
import { ApplyWebFonts } from "@/features/fonts/ApplyWebFonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CenterStageLayout>
          <TanstackProvider>{children}</TanstackProvider>
        </CenterStageLayout>
        <ApplyWebFonts />
      </body>
    </html>
  )
}
