import type { Metadata } from "next"

import "./globals.css"

import TanstackProvider from "@/features/tanstack/components/TanstackProvider"
import CenterStageLayout from "@/features/layout/components/CenterStageLayout"
import { ApplyWebFonts } from "@/features/fonts/ApplyWebFonts"
import { EchoProvider } from "@/components/EchoProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <EchoProvider>
          <CenterStageLayout>
            <TanstackProvider>{children}</TanstackProvider>
          </CenterStageLayout>
        </EchoProvider>
        <ApplyWebFonts />
      </body>
    </html>
  )
}
